In [1]:
import pandas as pd

In [4]:
df= pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [5]:
df

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
...,...,...,...,...,...,...,...,...,...,...,...
9995,2005,USA,Gasoline,All-wheel drive,4,2470,6,271.0,4690,18.9,27.4
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0
9997,2014,USA,Gasoline,All-wheel drive,3,2480,6,267.0,4590,18.4,28.1
9998,2004,USA,Hybrid,Rear-wheel drive,5,2180,6,270.0,4450,20.9,32.2


In [6]:
df.count()

model_year             10000
origin                 10000
fuel_type              10000
drivetrain             10000
num_doors              10000
engine_displacement    10000
num_cylinders          10000
horsepower              9123
vehicle_weight         10000
acceleration            9736
fuel_efficiency_mpg    10000
dtype: int64

In [27]:
df['fuel_type'].value_counts()

fuel_type
Gasoline    6913
Diesel      2053
Hybrid      1034
Name: count, dtype: int64

In [35]:
df.isna().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [46]:
asia_df=df[df['origin']=='asia']
asia_df['fuel_efficiency_mpg'].max()

np.float64(41.2)

In [47]:
df['horsepower'].median()

np.float64(254.0)

In [48]:
df['horsepower'].value_counts()

horsepower
252.0    174
246.0    168
256.0    168
259.0    165
253.0    165
        ... 
322.0      1
330.0      1
175.0      1
178.0      1
320.0      1
Name: count, Length: 153, dtype: int64

In [55]:
median_df=df['horsepower'].fillna(252.0)

In [56]:
median_df.median()

np.float64(252.0)

In [79]:
df_final=asia_df[['vehicle_weight','model_year']].head(7)

In [80]:
x=df_final.values

In [81]:
x

array([[3870, 2006],
       [4210, 2008],
       [4240, 1996],
       [4490, 1989],
       [4510, 1994],
       [4260, 2007],
       [4310, 1992]])

In [82]:
xtx=x.T.dot(x)

In [83]:
xtx

array([[127902500,  59738830],
       [ 59738830,  27968386]])

In [ ]:
import numpy as np
xtx_invert=np.linalg.inv(xtx)

In [85]:
xtx_invert

array([[ 3.29090918e-06, -7.02918875e-06],
       [-7.02918875e-06,  1.50496890e-05]])

In [86]:
y=np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [87]:
w=xtx_invert.dot(x.T).dot(y)

In [88]:
w.sum()

np.float64(0.7996290105453119)