In [2]:
import numpy as np

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
np.full(10,2)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
a=np.array([1,5,10,20,40])
a

array([ 1,  5, 10, 20, 40])

In [7]:
a[2]

np.int64(10)

In [8]:
np.arange(9,20)

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [9]:
np.linspace(2,10,5)

array([ 2.,  4.,  6.,  8., 10.])

**Multi-Dimensional Array**

In [10]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
n=np.array([[1,2,3],[4,5,6]])

In [12]:
n[0,1]=20
n

array([[ 1, 20,  3],
       [ 4,  5,  6]])

In [13]:
n[1]=[40,50,60]
n

array([[ 1, 20,  3],
       [40, 50, 60]])

In [14]:
n[:,2]=[30,6]
n

array([[ 1, 20, 30],
       [40, 50,  6]])

In [15]:
n[:,1]

array([20, 50])

**Randomly Generated Array**

In [16]:
np.random.seed(20)
np.random.rand(5,2)

array([[0.5881308 , 0.89771373],
       [0.89153073, 0.81583748],
       [0.03588959, 0.69175758],
       [0.37868094, 0.51851095],
       [0.65795147, 0.19385022]])

In [17]:
np.random.seed(2)
np.random.randint(low=1, high=101, size=(5,2))

array([[41, 16],
       [73, 23],
       [44, 83],
       [76,  8],
       [35, 50]], dtype=int32)

**Element-wise operations**

In [18]:
a=np.random.randint(low=1,high=50, size=(3,3))
a

array([[32, 12, 22],
       [48, 32, 27],
       [21, 38, 40]], dtype=int32)

In [19]:
b=a+a
b

array([[64, 24, 44],
       [96, 64, 54],
       [42, 76, 80]], dtype=int32)

In [20]:
c=a*b
c

array([[2048,  288,  968],
       [4608, 2048, 1458],
       [ 882, 2888, 3200]], dtype=int32)

Comparision Opeartors 

In [21]:
c>=b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

**Summarizing Opeartions**

In [25]:
print(c.std())

1271.8204314589946


**Identity Matrix**

In [27]:
a=np.eye(3)

In [29]:
b=np.random.randint(low=0, high=3 , size=(3,3))

In [35]:
c=a*b
c

array([[0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 2.]])

**Matrix Inverse**

In [37]:
v=np.array([[4,7],[2,6]])
v_inv=np.linalg.inv(v)
v_inv

array([[ 0.6, -0.7],
       [-0.2,  0.4]])

In [38]:
v.dot(v_inv)

array([[ 1.00000000e+00, -1.11022302e-16],
       [-1.11022302e-16,  1.00000000e+00]])